# Generated by Django 5.1.7 on 2025-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('flag_url', models.URLField()),
                ('youtube_link', models.URLField()),
                ('wikipedia_link', models.URLField()),
            ],
        ),
    ]
